### PR TITLE
Update Japanese translation

### PR DESCRIPTION
**Pull request by Rukoto**
Changes:

- Fixed many translation mistakes
- Replaced some keywords with appropriate ones
- Added a missing resource to ja-JP.dll
(Resources not necessary for Japanese have been omitted from ja-JP.dll. ex: Right To Left)

### CODE REVIEW

**Comment by Rukoto** [comment]
First of all, I appreciate that you confirmed the content.

The content of this pull request was reported before Ivo finished development,
As I needed to make lots of corrections, the report was delayed and eventually was not included in the Classic Shell.

In a famous Japanese forum, I know that these files were published in Classic Shell's forum and in my repository,
In this forum, there is no problem report on my translation.
However, I realize that this fact is irrelevant to the quality of the file.

Are you planning to set up a forum, not limited to topics of translation?
In addition to translation, I feel that a place where users can talk is necessary.

**Comment by coddec** [comment]
@Rukoto 
First of all, thank you very much for the hard work, we appreciate your contribution and other's contribution!

As all of us know that people makes mistakes, that's why I always want to double confirm 😄 

Yes, I saw the issue here https://github.com/passionate-coder/Classic-Start/issues/7
For sure I agree with you that 
> In addition to translation, I feel that a place where users can talk is necessary.

I'll see what can we do.

Meanwhile, anyone has thoughts on using [Gitter](https://gitter.im) as a replacement of forum?
The reason behind it is, most of free forum provider seems either put lot's of ADs or short-life product (Unreliable) Gitter otherwise seems at least can be a place to gather the community together and talk to each other, especially for non-coders.
One important thing that I want to know is are there any limitation of no. of users in a public room? Anyone can confirm that for me? If no, I guess we can move on to use that replacement of forum.

**Comment by coddec** [comment]
@ge0rdi @XenHat @Quentinix 
Anyone? Any thoughts?
Should we merge?
😃

**Comment by coddec** [comment]
@Rukoto @ge0rdi 
Probably merge of translation is fine.
One question is how did you produce ja-JP.dll? If it's utilized other parts from classic shell e.g. .bat and other resource file, does it mean that there are other parts need to be corrected or they are all here?
Sorry for this type of dumb question...
Correct if I'm wrong.

Thanks!

**Comment by Rukoto** [comment]
I made ja-JP.dll using [Resource Hacker](http://www.angusj.com/resourcehacker/).
In en-US.dll in the repository, some resources required for translation are missing.
So I first made en-US.dll which is a template.

1. Get "Resource Hacker" and run it.
1. Import [L10N], [Version Info], [Manifest] from en-US.dll in the repository from "Add from a Resouce file".
1. Import the [Dialog], [String Table] group from 'ClassicExplorer32.dll', 'ClassicIEDLL_32.dll', 'ClassicStartMenuDLL.dll', 'ClassicShellUpdate.exe' which exists in the installation folder of Classic Shell.
1. Delete only "7" in [String Table] group .
1. Correct the contents (version number etc.) of [Version Info].
1. Save it as en-US.dll. (However, you should prepare the template en-US.dll which was originally built in the development environment.)
1. Edit the string in en-US.dll with Resource Hacker and save it as ja-JP.dll.

I am sorry, but I do not know about the correct way to build en-US.dll.

By exporting to RC file, we can proofread translations by someone else.
When managing translation changes, you need to be careful to publish a text file (eg *.rc) and synchronize it with the DLL file.

**Comment by coddec** [comment]
Hi @Rukoto thank you very much for those important details!
I guess we need to work on this together @ge0rdi @XenHat @Quentinix 
To double confirm there's no issue with the complete set of the program?
Or should we???

@Rukoto You've successfully compiled and ran the program I guess?

**Comment by Rukoto** [comment]
@coddec 
AppVeyor succeeded in building. I think that I have not used the program for a while but it does not matter.
If the language file version is higher than the main version, the language file was not applied.
This was an unexpected discovery:open_mouth:

**Comment by coddec** [comment]
@Rukoto 
Aha 👍 
That's why double or triple confirm kicks in 😃 
Good catch!
Well... I can tell you that... you probably know more about classic shell than I do 😉😉
That's why I want our team check it out 🤣 
If it's only me, I probably have clicked on Merge pull request, till later we found the issue... and endless debug process begins 😆

**Comment by XenHat** [comment]
Due to rebranding and name change, these translations need to be updated. :(
cc @Rukoto

**Comment by coddec** [comment]
@XenHat Just a quick reminder, we might need to be aware of versioning & translation problem mentioned earlier within this issue, just in case 👍

**Comment by XenHat** [comment]
> Not really relevant to this issue: Was digging on alternatives of transifex, no luck
I don't really see the need for a big platform like that for this project.
The files could be relocated somewhere more obvious, perhaps, but I prefer plan text editing when it comes to this.

**Comment by coddec** [comment]
All good, thought it might make crowdsourcing easier, but yes, I agree it can be over kill for now😄

**Comment by Rukoto** [comment]
@XenHat Thank you for doing a detailed investigation.
It is very useful to understand what kind of procedure the translation is realized.

@coddec It is regrettable that the quality of Japanese translation will remain low,
At this stage I decided that this pull request should be closed.

I think that it is possible to immediately replace the text file, but I will skip this time.
Thank you.

**Pull request closed without merging**
